In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/home/faraz/Documents/Verzeo May ML 1/Data/Social_Network_Ads.csv")

In [3]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
df.corr()        #   Checking correlation between input and output

User ID       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.000721         0.071097   0.007120
Age             -0.000721  1.000000         0.155238   0.622454
EstimatedSalary  0.071097  0.155238         1.000000   0.362083
Purchased        0.007120  0.622454         0.362083   1.000000

In [5]:
x = df[["Age","EstimatedSalary"]].values      # Input 

In [6]:
y = df["Purchased"].values     # Output

# Train Test

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
train_x , test_x , train_y , test_y = train_test_split(x,y,test_size = 0.2 , random_state=0)

## As in our data -->  Age and salary values are not close
##  So we use ***Standardisation or Normalization***

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
sc = StandardScaler()

In [11]:
train_x = sc.fit_transform(train_x)       #  Transforming our data
test_x = sc.fit_transform(test_x)

In [12]:
test_x

array([[-0.49618606,  0.56021375],
       [ 0.2389044 , -0.59133674],
       [-0.03675452,  0.18673792],
       [-0.49618606,  0.31122986],
       [-0.03675452, -0.59133674],
       [-0.77184498, -1.52502632],
       [-0.40429975, -1.68064126],
       [ 0.05513178,  2.33422397],
       [-1.59882175, -0.03112299],
       [ 1.06588117, -0.80919764],
       [-0.49618606, -0.62245972],
       [-0.67995868, -0.43572181],
       [ 0.14701809, -0.43572181],
       [ 0.33079071,  0.24898389],
       [-1.41504914,  0.52909077],
       [-0.31241345,  1.49390334],
       [ 0.14701809,  0.24898389],
       [-1.50693545,  0.49796778],
       [ 1.80097163,  1.89850216],
       [-0.03675452, -1.46278035],
       [-0.03675452, -0.6847057 ],
       [ 1.06588117,  2.33422397],
       [ 0.51456332, -0.56021375],
       [ 1.06588117,  1.1204275 ],
       [-1.13939022, -1.27604243],
       [ 1.24965379,  2.24085501],
       [-0.67995868,  0.56021375],
       [-0.58807237,  0.34235285],
       [ 0.14701809,

In [13]:
from sklearn.linear_model import LogisticRegression


In [21]:
classifier = LogisticRegression()

In [15]:
classifier.fit(train_x,train_y)

LogisticRegression()

In [16]:
pred_y = classifier.predict(test_x)

In [17]:
pred_y-test_y

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0, -1,  0,  0,  1,  0,  0,  0])

 # For checking our prediction

In [18]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [19]:
accuracy_score(test_y,pred_y)    #  it gives the accuracy 

0.8875

In [20]:
confusion_matrix(test_y,pred_y)

array([[52,  6],
       [ 3, 19]])