# *Numpy*

In [1]:
import numpy as np


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], np.int64)


print(arr[0])
print(arr.dtype)



1
int64




## ***np.int64 is dtype of our array  -->  By Default it is int32     ,     np.int64 is optional***            
        




In [3]:
arr_2D = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])  # 2D Array

print(arr_2D.shape)     #    Shape will return Dimension of array
print(arr_2D.dtype)

(3, 3)
int64


## ***np.zeros((2,5))  -->   Create an array of size (2,5) and initialize it with zeros   ,    dtype -> float64***

In [4]:
arr_zero = np.zeros((2, 5),np.int64)

print(arr_zero)
print(arr_zero.shape)  #  2,5
print(arr_zero.dtype)  # float64 is default
print(arr_zero.size)   # 10

[[0 0 0 0 0]
 [0 0 0 0 0]]
(2, 5)
int64
10


## ***np.arange(15)  -->   Create an array of size 15 and initialize it with int (0~14)   ,    dtype -> int64***


In [5]:
arr_range = np.arange(15)

print(arr_range)  # 0~14
print(arr_range.dtype)   # Int 64

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int64


## ***np.linspace(1, 20, 35)  -->   Create an array of size 35 initialize number btw (1~20) in equal space    ,    dtype -> float64***

In [6]:
arr_line = np.linspace(1, 20, 35)     #   35 values 

print(arr_line)
print(arr_line.dtype)   # Float64
print(arr_line.size)   # 35

[ 1.          1.55882353  2.11764706  2.67647059  3.23529412  3.79411765
  4.35294118  4.91176471  5.47058824  6.02941176  6.58823529  7.14705882
  7.70588235  8.26470588  8.82352941  9.38235294  9.94117647 10.5
 11.05882353 11.61764706 12.17647059 12.73529412 13.29411765 13.85294118
 14.41176471 14.97058824 15.52941176 16.08823529 16.64705882 17.20588235
 17.76470588 18.32352941 18.88235294 19.44117647 20.        ]
float64
35


## ***np.empty((4, 6))  -->   Create an 2d-array and initialize it with garbage value   ,    dtype -> float64***

In [7]:
arr_empty = np.empty((4, 6))


print(arr_empty)
print(arr_empty.dtype)

[[4.64003473e-310 0.00000000e+000 6.93131217e-310 6.93131221e-310
  6.93131221e-310 6.93131221e-310]
 [6.93131221e-310 6.93131157e-310 6.93131221e-310 6.93131221e-310
  6.93131078e-310 6.93131222e-310]
 [6.93131222e-310 6.93131222e-310 6.93131219e-310 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]
float64


## ***np.empty_like(arr)  --> Creates array like array passed and initialize it with garbage values***

In [8]:
arr_like = np.empty_like(arr)

print(arr_like)
print(arr_like.dtype)

[                   0                    0 -1709503944649611374
      140290460588144      140290438886224  6884689792621568439
      140290460580000      140290438886224  6205697083158548555
      140291214605360]
int64






## ***np.identity(10)   -->  Creates identity matrix of size 10*10   ,   Dtype  -> float64***






In [9]:
arr_Identity_matrix = np.identity(10)

print(arr_Identity_matrix)
print(arr_Identity_matrix.shape)
print(arr_Identity_matrix.dtype)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
(10, 10)
float64


In [10]:
y = np.arange(10, 20, 1)  # From 10 to 20 in step of 1
n = np.random.randint(10, 20, 5)  # 5 Random numbers from between 10 to 20

print(y)
print(n)

[10 11 12 13 14 15 16 17 18 19]
[10 12 18 12 12]


#                                        Resizing  Array

In [11]:
arr = np.arange(33)
arr = arr.reshape(3, 11)           # It reshapes the 1d-array to form 2d-array
                                   # Three rows containing 11 elements each

print(arr)
print("\n\n")

arr = arr.ravel()                # Change back to 1d-array
print(arr)                       # arr.ravel() doesnot change original array it returns new array
print("\n\n")

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28 29 30 31 32]]



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32]





# Axis in numpy is like dimensions in Matrix
 # 2  3  4
#                                                       4  5  6
  #                                                     7  8  9
  
  

  # axis=0  --> Horizontal Part
   # axis=1  --> Vertical Part 

In [12]:
x = arr_2D.sum(axis=0)      # Sum of column ( Horizontal )

print(arr_2D)
print("\n")
print(x)
print("\n")

x = arr_2D.sum(axis=1)      # Sum of rows ( Vertical )
print(x)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


[ 9 12 15]


[ 6 12 18]


In [13]:
print(f"{arr_2D} \n")
print(f"{arr_2D.T}\n")           # Arr.T    --> Transposes the array
print(arr_2D.ndim)     #  Returns number of dimensions
print(arr_2D.nbytes)     #  Returns Total number of Bytes consumed by array

[[1 2 3]
 [3 4 5]
 [5 6 7]] 

[[1 3 5]
 [2 4 6]
 [3 5 7]]

2
72


In [14]:

print(arr.argmax())    #  Returns index of max element  in 1 Dimension Array
print(arr.argmin())    #  Returns index of min element  in 1 Dimension Array

print(arr_2D.argmax(axis=0))    # Returns index
print(arr_2D.argmax(axis=1))    # Returns index

32
0
[2 2 2]
[2 2 2]


# ***Operations in Array***

In [15]:

x = np.arange(10)
y = np.arange(8, 18, 1)  # Random numbers From 8 to 18 in step of 1


print(x)
print("\n")

print(y)
print("\n")

print(x+y)      # Addition of array
print("\n")

print(x*y)      # Multiplication of array
print("\n")

print(np.sqrt(x))     # Finding Square root
print("\n")

x = x+5           #         Adding 5 to each element
x = x*5           #         Multiplying 5 to each element of array

print(np.sin(x))        #       Sin , Cos , tan , log
print("\n")

print(np.sort(x))       #       Sorting an array
print("\n")


print(x.max())
print(x.min())
print(x.sum())

z = np.where(x > 8)  # Returns index of condition
print("\n")
print(z)


[0 1 2 3 4 5 6 7 8 9]


[ 8  9 10 11 12 13 14 15 16 17]


[ 8 10 12 14 16 18 20 22 24 26]


[  0   9  20  33  48  65  84 105 128 153]


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


[-0.13235175 -0.98803162 -0.42818267  0.74511316  0.85090352 -0.26237485
 -0.99975517 -0.30481062  0.82682868  0.77389068]


[25 30 35 40 45 50 55 60 65 70]


70
25
475


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)


# Some Important Operations on numpy Array

In [16]:
#                   *****       Joining Numpy Arrays        *****

n1 = np.vstack((x, y))                   # Creates vertical Stack
n2 = np.hstack((x, y))                   # Creates Horizontal Stack
n3 = np.column_stack((x, y))             # Creates Stack of columns


#                   *****       Mathematical functions      *****

n4 = np.intersect1d(x, y)  # .             Intersection of two arrays
n5 = np.setdiff1d(x, y)  # .           Difference of two arrays  -->  x-y

n6 = np.sum((x, y), axis=0)  # .                Adding Column Elements
n7 = np.sum((x, y), axis=1)  # .                Adding Row Elements

n8 = np.mean(x)  # .                Mean of x
n9 = np.std(x)  # .                Standard deviation of x
n10 = np.median(x)  # .                Median of x

print(f"{n1}\n\n{n2}\n\n{n3}\n\n{n4}\n\n{n5}\n\n{n6}\n\n{n7}\n\n{n8}\n\n{n9}\n\n{n10}\n\n")


[[25 30 35 40 45 50 55 60 65 70]
 [ 8  9 10 11 12 13 14 15 16 17]]

[25 30 35 40 45 50 55 60 65 70  8  9 10 11 12 13 14 15 16 17]

[[25  8]
 [30  9]
 [35 10]
 [40 11]
 [45 12]
 [50 13]
 [55 14]
 [60 15]
 [65 16]
 [70 17]]

[]

[25 30 35 40 45 50 55 60 65 70]

[33 39 45 51 57 63 69 75 81 87]

[475 125]

47.5

14.361406616345072

47.5


